service: weatherapp-server

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: ap-south-1

functions:
  api:
    handler: handler.handler
    timeout: 10 #seconds
    memorySize: 256 #mb
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
